apiVersion: v1
kind: Service
metadata:
  name: hia-backend
  namespace: {{ .Values.global.namespace }}
  labels: { app: hia-backend }
spec:
  type: ClusterIP
  selector: { app: hia-backend }
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
