apiVersion: apps/v1
kind: Deployment
metadata:
  name: hia-backend
  labels:
    app: hia-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hia-backend
  template:
    metadata:
      labels:
        app: hia-backend
    spec:
      containers:
        - name: api
          image: hiaacr-abewdkh4fnczddgz.azurecr.io/health-insights-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Asia/Kolkata"
          readinessProbe:
            httpGet:
              path: /docs
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
