apiVersion: v1
kind: Service
metadata:
  name: hia-backend
  labels:
    app: hia-backend
spec:
  type: LoadBalancer
  selector:
    app: hia-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
