apiVersion: apps/v1
kind: Deployment
metadata:
  name: hia-frontend
  labels:
    app: hia-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hia-frontend
  template:
    metadata:
      labels:
        app: hia-frontend
    spec:
      containers:
        - name: web
          image: hiaacr-abewdkh4fnczddgz.azurecr.io/health-insights-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
