name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Backend image (adjust context/dockerfile paths if different)
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/backend.Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/health-insights-backend:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/health-insights-backend:latest

      # Frontend image (adjust context/dockerfile paths if different)
      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/frontend.Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/health-insights-frontend:${{ github.sha }}
            ${{ env.ACR_LOGIN_SERVER }}/health-insights-frontend:latest
